# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a251689fe2c9dbbc9bae32031162df989752e2e178b745d1a2f90c1979272e5fbb38e5b43fb5629a40ede0b3fd8958b3bc8a13a38b332356b0974a3a8c843d2

test:
  secret_key_base: 7ec058f05fe649308e5e566086efc18f11130f8196da8a64567347aa812d28a62be55b4dedd140aa7e086619dd7e40a85eb3b0ebc5c26e1483f17d8fd931e7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
